const projectInfo = [
    {
      image: './img/img-placeholder1.png',
      image1: './img/img-placeholder1.png',
      title: 'Professional Art<br>Printing',
      text: 'A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry´s standard.',
      mobileModuleTitle: 'Multi-Post Stories',
      mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
      'electronic typesetting, remaining essent'],
      desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
      'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
      tools: ['HTML', 'Bootstrap', 'Ruby'],
      live: 'https://eamador1.github.io/portfolio/',
      code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },
    {
      image: './img/image-background2.png',
      image1: './img/img-placeholder1.png',
      title: 'Data Dashboard<br>Healthcare',
      text: 'A daily selection of privately personalized reads; no accounts or sign-ups required.Has been the industry´s standard.',
      mobileModuleTitle: 'Multi-Post Stories',
      mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
      'electronic typesetting, remaining essent'],
      desktopModuleTitle: '',
      desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
      'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
      tools: ['HTML', 'Bootstrap', 'Ruby'],
      live: 'https://eamador1.github.io/portfolio/',
      code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },
    {
          image: './img/image-background3.png',
          image1: './img/img-placeholder1.png',
          title: 'Website Portfolio', 
          text: 'A daily selection of privately personalized reads; no accounts or sign-ups required.Has been the industry´s standard.',
          mobileModuleTitle: 'Multi-Post Stories',
          mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
          'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
          'electronic typesetting, remaining essent'],
          desktopModuleTitle: '',
          desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
          'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
          'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
          'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
          tools: ['HTML', 'Bootstrap', 'Ruby'],
          live: 'https://eamador1.github.io/portfolio/',
          code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },
    {
      image: './img/img-placeholder1.png',
      image1: './img/img-placeholder1.png',
      title: 'Professional Art<br>PrintingData',
      text: 'A daily selection of privately personalized reads; no accounts or sign-ups required. Has been the industry´s standard.',
      mobileModuleTitle: 'Multi-Post Stories',
      mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
      'electronic typesetting, remaining essent'],
      desktopModuleTitle: '',
      desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
      'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
      tools: ['HTML', 'Bootstrap', 'Ruby'],
      live: 'https://eamador1.github.io/portfolio/',
      code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },
    {
      image: './img/image-background2.png',
      image1: './img/img-placeholder1.png',
      title: 'Data Dashboard<br>Healthcare',
      text: 'A daily selection of privately personalized reads; no accounts or sign-ups required.Has been the industry´s standard.',
      mobileModuleTitle: 'Multi-Post Stories',
      mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
      'electronic typesetting, remaining essent'],
      desktopModuleTitle: '',
      desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
      'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
      tools: ['HTML', 'Bootstrap', 'Ruby'],
      live: 'https://eamador1.github.io/portfolio/',
      code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },
    {
      image: './img/image-background3.png',
      image1: './img/img-placeholder1.png',
      title: 'Website Portfolio', 
      text: 'A daily selection of privately personalized reads; no accounts or sign-ups required.Has been the industry´s standard.',
      mobileModuleTitle: 'Multi-Post Stories',
      mobileModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into',
      'electronic typesetting, remaining essent'],
      desktopModuleTitle: '',
      desktopModuleText: ['Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,', 
      'when an unknown printer took a galley of type and scrambled it in 1960s.<br>',
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry´s standard dummy text ever since the 1500s,',
      'when an unknown printer took a galley of type and scrambled it in 1960s with the releax  map lapora verita.'],
      tools: ['HTML', 'Bootstrap', 'Ruby'],
      live: 'https://eamador1.github.io/portfolio/',
      code: 'https://github.com/eamador1/portfolio/blob/main/index.html',
    },  
    ];
  
      export { projectInfo };